insert into local.todo_entity(id, name, description, priority, status, created_date, due_date, updated_date)
VALUES ("1", "Groceries", "Buy groceries", "High", "Pending", NOW(), NOW(), NOW()),
("2", "Laundry", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("3", "Cooking", "Description", "Medium", "Pending", NOW(), NOW(), NOW()),
("4", "Sweeping", "Description", "Medium", "Pending", NOW(), NOW(), NOW()),
("5", "Shower", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("6", "Gym", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("7", "Work", "Description", "Medium", "Pending", NOW(), NOW(), NOW()),
("8", "Eat", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("9", "Sleep", "Description", "High", "Pending", NOW(), NOW(), NOW()),
("10", "Relax", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("11", "Documetation", "Description", "High", "Pending", NOW(), NOW(), NOW()),
("12", "Immigration", "Description", "Medium", "Pending", NOW(), NOW(), NOW()),
("13", "Application", "Description", "High", "Pending", NOW(), NOW(), NOW())
("2", "Laundry", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("3", "Cooking", "Description", "Medium", "Pending", NOW(), NOW(), NOW()),
("4", "Sweeping", "Description", "Medium", "Pending", NOW(), NOW(), NOW()),
("5", "Shower", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("6", "Gym", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("7", "Work", "Description", "Medium", "Pending", NOW(), NOW(), NOW()),
("8", "Eat", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("9", "Sleep", "Description", "High", "Pending", NOW(), NOW(), NOW()),
("10", "Relax", "Description", "Low", "Pending", NOW(), NOW(), NOW()),
("11", "Documetation", "Description", "High", "Pending", NOW(), NOW(), NOW()),
("12", "Immigration", "Description", "Medium", "Pending", NOW(), NOW(), NOW()),
("13", "Application", "Description", "High", "Pending", NOW(), NOW(), NOW())