insert into local.todo(id, name, description, priority, status, created_date, due_date, updated_date)
VALUES (1, 'Movies', 'Deformity of orbit NOS', 'High', 'Pending', now(), now(), now()),
(2, 'Books', 'Aftrcre traum fx vertebr', 'High', 'Pending', now(), now(), now()),
(3, 'Kids', 'Ben crcnoid sm intst NOS', 'Medium', 'Completed', now(), now(), now()),
(4, 'Sports', 'Thalassemia, unspecified', 'Low', 'Pending', now(), now(), now()),
(5, 'Health', 'Adv eff antipruritics', 'High', 'Completed', now(), now(), now()),
(6, 'Garden', 'Enterococcus group d', 'High', 'Completed', now(), now(), now()),
(7, 'Tools', 'Retain placenta NOS-unsp', 'Low', 'Pending', now(), now(), now()),
(8, 'Outdoors', 'Renal & ureteral dis NEC', 'High', 'Pending', now(), now(), now()),
(9, 'Books', 'Hypertrophy of clitoris', 'High', 'Pending', now(), now(), now()),
(10, 'Music', 'Open wound of trunk NEC', 'Medium', 'Completed', now(), now(), now()),
(11, 'Sports', 'Hydrops fetalis:isoimm', 'Medium', 'Completed', now(), now(), now()),
(12, 'Automotive', 'Retinal defect NOS', 'High', 'Pending', now(), now(), now()),
(13, 'Garden', 'Cl skul base fx-mod coma', 'High', 'Completed', now(), now(), now()),
(14, 'Tools', 'Ca in situ skin arm', 'Low', 'Pending', now(), now(), now()),
(15, 'Books', 'Sev nonprolf db retinoph', 'Low', 'Pending', now(), now(), now()),
(16, 'Jewelry', 'TB of kidney-histo dx', 'High', 'Pending', now(), now(), now()),
(17, 'Books', 'Complx febrile convulsns', 'High', 'Completed', now(), now(), now()),
(18, 'Computers', 'Tuberous sclerosis', 'Medium', 'Completed', now(), now(), now()),
(19, 'Automotive', 'NB subarachnoid hemorr', 'Low', 'Pending', now(), now(), now()),
(20, 'Garden', 'Tritan defect', 'Medium', 'Pending', now(), now(), now()),
(21, 'Automotive', 'Spacecraft acc-occupant', 'Low', 'Completed', now(), now(), now()),
(22, 'Tools', 'Fet damg d/t virus-unsp', 'Low', 'Pending', now(), now(), now()),
(23, 'Toys', 'Nonspcf serlgc evdnc hiv', 'Low', 'Pending', now(), now(), now()),
(24, 'Beauty', 'Opn cortex lac-deep coma', 'Low', 'Pending', now(), now(), now()),
(25, 'Industrial', 'Hit by train-pedestrian', 'High', 'Pending', now(), now(), now()),
(26, 'Garden', 'Acute nephritis NEC', 'High', 'Pending', now(), now(), now()),
(27, 'Tools', 'Onchocerciasis', 'Medium', 'Pending', now(), now(), now()),
(28, 'Beauty', 'Meningitis NOS', 'High', 'Completed', now(), now(), now()),
(29, 'Kids', 'Congenital chordee', 'Low', 'Pending', now(), now(), now()),
(30, 'Tools', 'Cumltv trma-repetv motn', 'Low', 'Pending', now(), now(), now()),
(31, 'Kids', 'Adv eff metal anti-inf', 'Low', 'Completed', now(), now(), now()),
(32, 'Baby', 'Chromosome anomaly NOS', 'Low', 'Pending', now(), now(), now()),
(33, 'Music', 'Erythematous cond NOS', 'High', 'Completed', now(), now(), now()),
(34, 'Shoes', 'Need prphyl vc vrl hepat', 'Medium', 'Pending', now(), now(), now()),
(35, 'Tools', 'Second malig neo kidney', 'High', 'Completed', now(), now(), now()),
(36, 'Baby', 'Screen mal neop-oral cav', 'Medium', 'Completed', now(), now(), now()),
(37, 'Toys', '2nd deg burn back', 'Low', 'Pending', now(), now(), now()),
(38, 'Games', 'W/craft fall NOS-skier', 'Medium', 'Completed', now(), now(), now()),
(39, 'Music', 'Open wound of lip', 'Low', 'Pending', now(), now(), now()),
(40, 'Books', 'Prs ara wo inf w ntr/st', 'Medium', 'Pending', now(), now(), now()),
(41, 'Automotive', 'Intestin TB NEC-micro dx', 'Low', 'Pending', now(), now(), now()),
(42, 'Sports', 'Preg w hx ectopic preg', 'High', 'Pending', now(), now(), now()),
(43, 'Sports', 'Mech loosening pros jt', 'Low', 'Pending', now(), now(), now()),
(44, 'Music', 'Ulcer of ankle', 'Medium', 'Completed', now(), now(), now()),
(45, 'Games', 'Siderosis', 'Low', 'Completed', now(), now(), now()),
(46, 'Industrial', 'Acute chest syndrome', 'High', 'Pending', now(), now(), now()),
(47, 'Grocery', 'Resp sys/chest symp NEC', 'Medium', 'Pending', now(), now(), now()),
(48, 'Home', 'Shrt lst uni nral hdache', 'Medium', 'Pending', now(), now(), now()),
(49, 'Music', 'Problems with learning', 'Medium', 'Pending', now(), now(), now()),
(50, 'Beauty', 'Vaccin for rabies', 'High', 'Pending', now(), now(), now()),
(51, 'Health', 'Acute syphil meningitis', 'High', 'Pending', now(), now(), now()),
(52, 'Outdoors', 'Malig neo brain NEC', 'Low', 'Pending', now(), now(), now()),
(53, 'Home', 'Dentl caries-pit/fissure', 'Low', 'Completed', now(), now(), now()),
(54, 'Industrial', 'Mucopolysaccharidosis', 'Low', 'Pending', now(), now(), now()),
(55, 'Shoes', 'Oth func dsdr bladder', 'Medium', 'Completed', now(), now(), now()),
(56, 'Kids', 'Chr atticoantral sup OM', 'Low', 'Pending', now(), now(), now()),
(57, 'Automotive', 'Fx humer, med condyl-opn', 'Low', 'Completed', now(), now(), now()),
(58, 'Kids', 'Adv eff antiviral drugs', 'High', 'Pending', now(), now(), now()),
(59, 'Clothing', 'Sec DM unsp uncontrold', 'Low', 'Completed', now(), now(), now()),
(60, 'Grocery', 'Orbital tenonitis', 'Medium', 'Completed', now(), now(), now()),
(61, 'Beauty', 'Anphyl react oth sp food', 'Medium', 'Completed', now(), now(), now()),
(62, 'Clothing', 'Colosty/enter comp-mech', 'Medium', 'Completed', now(), now(), now()),
(63, 'Jewelry', 'Injury-cut instrument', 'Low', 'Pending', now(), now(), now()),
(64, 'Computers', 'Episodc cluster headache', 'Medium', 'Pending', now(), now(), now()),
(65, 'Electronics', 'Traumatic cataract NOS', 'High', 'Completed', now(), now(), now()),
(66, 'Sports', 'Hemarthrosis-mult jts', 'High', 'Pending', now(), now(), now()),
(67, 'Books', 'Cong esoph fistula/atres', 'Low', 'Completed', now(), now(), now()),
(68, 'Industrial', 'Urethritis NEC', 'Medium', 'Pending', now(), now(), now()),
(69, 'Tools', 'Ventricular flutter', 'Low', 'Pending', now(), now(), now()),
(70, 'Kids', 'Ophthalmia nodosa', 'Medium', 'Completed', now(), now(), now()),
(71, 'Electronics', 'Prophylactic isolation', 'Low', 'Completed', now(), now(), now()),
(72, 'Automotive', 'Matern urine dis aff NB', 'Low', 'Completed', now(), now(), now()),
(73, 'Games', '1st deg burn thigh', 'High', 'Completed', now(), now(), now()),
(74, 'Sports', 'Cl skull fx NEC-brf coma', 'Low', 'Pending', now(), now(), now()),
(75, 'Beauty', 'Open wnd ear drum-compl', 'Low', 'Completed', now(), now(), now()),
(76, 'Electronics', 'Obstruc/fet malpos-deliv', 'High', 'Completed', now(), now(), now()),
(77, 'Baby', 'Fracture ulna NOS-closed', 'High', 'Completed', now(), now(), now()),
(78, 'Outdoors', 'Adhesive mid ear dis NEC', 'High', 'Completed', now(), now(), now()),
(79, 'Electronics', 'Shldr/upper arm inj NOS', 'Low', 'Pending', now(), now(), now()),
(80, 'Baby', 'Nonsp abn find-body NEC', 'Medium', 'Pending', now(), now(), now()),
(81, 'Tools', '80-89% bdy brn/30-39% 3d', 'Low', 'Completed', now(), now(), now()),
(82, 'Beauty', 'Malign neopl prepuce', 'High', 'Pending', now(), now(), now()),
(83, 'Computers', 'Child physical abuse', 'High', 'Completed', now(), now(), now()),
(84, 'Toys', 'Hb-SS disease w/o crisis', 'Medium', 'Pending', now(), now(), now()),
(85, 'Beauty', 'Psorospermiasis', 'Low', 'Completed', now(), now(), now()),
(86, 'Beauty', 'Yaba monkey tumor virus', 'Low', 'Pending', now(), now(), now()),
(87, 'Garden', 'Prim uterine inert-deliv', 'High', 'Pending', now(), now(), now()),
(88, 'Shoes', 'Tympnoscler-tymp/ossicle', 'Medium', 'Pending', now(), now(), now()),
(89, 'Home', 'Adv eff smallpox vaccine', 'Medium', 'Pending', now(), now(), now()),
(90, 'Sports', 'Anomalies of toes NEC', 'Medium', 'Pending', now(), now(), now()),
(91, 'Industrial', 'Psychiatric follow-up', 'Low', 'Completed', now(), now(), now()),
(92, 'Clothing', 'Hiccough', 'High', 'Pending', now(), now(), now()),
(93, 'Computers', 'Diffuse cholesteatosis', 'Medium', 'Pending', now(), now(), now()),
(94, 'Beauty', 'Pois-irritant cathartics', 'High', 'Pending', now(), now(), now()),
(95, 'Home', 'Lt-date w/mal 1000-1249g', 'Low', 'Completed', now(), now(), now()),
(96, 'Books', 'Pois-coronary vasodilat', 'Medium', 'Pending', now(), now(), now()),
(97, 'Movies', 'Opn wnd shouldr w tendon', 'Medium', 'Pending', now(), now(), now()),
(98, 'Shoes', 'Idiopathic osteoporosis', 'Low', 'Completed', now(), now(), now()),
(99, 'Kids', 'Failed forceps NOS-deliv', 'High', 'Pending', now(), now(), now()),
(100, 'Automotive', 'Rubella-delivered w p/p', 'High', 'Completed', now(), now(), now()),
(101, 'Clothing', 'Cannabis abuse-unspec', 'Medium', 'Pending', now(), now(), now()),
(102, 'Garden', 'Large cell lymph inguin', 'Medium', 'Pending', now(), now(), now()),
(103, 'Industrial', 'Lack of water', 'High', 'Pending', now(), now(), now()),
(104, 'Books', 'Hx-drug allergy NOS', 'Low', 'Pending', now(), now(), now()),
(105, 'Industrial', 'Reiter''s disease', 'High', 'Pending', now(), now(), now()),
(106, 'Industrial', 'Poor fetal grth-antepart', 'Low', 'Pending', now(), now(), now()),
(107, 'Toys', 'Lat disl prox tibia-open', 'Medium', 'Pending', now(), now(), now()),
(108, 'Books', 'Acute pericarditis NOS', 'Medium', 'Pending', now(), now(), now()),
(109, 'Electronics', 'Opn wound site NOS-compl', 'Low', 'Pending', now(), now(), now()),
(110, 'Music', 'Cl skull vlt fx w/o coma', 'Low', 'Pending', now(), now(), now()),
(111, 'Computers', 'Local anterior staphylma', 'Medium', 'Completed', now(), now(), now()),
(112, 'Home', 'Insect bite trunk', 'High', 'Pending', now(), now(), now()),
(113, 'Industrial', 'Sec DM wo cmp nt st uncn', 'Medium', 'Completed', now(), now(), now()),
(114, 'Movies', 'Neuritis of preg-antepar', 'Low', 'Pending', now(), now(), now()),
(115, 'Tools', 'Palindrom rheum-l/leg', 'Low', 'Completed', now(), now(), now()),
(116, 'Automotive', 'Organic parasomnia NOS', 'Low', 'Pending', now(), now(), now()),
(117, 'Movies', 'Meth resis Staph carrier', 'Low', 'Pending', now(), now(), now()),
(118, 'Games', 'Gastroduodenal dis NEC', 'Low', 'Pending', now(), now(), now()),
(119, 'Games', '1st deg burn knee', 'Medium', 'Pending', now(), now(), now()),
(120, 'Jewelry', 'Sus amntc cav/mem nt fnd', 'Medium', 'Pending', now(), now(), now()),
(121, 'Health', 'Myl srcoma w rmsion', 'High', 'Pending', now(), now(), now()),
(122, 'Music', 'Mv coll w oth obj-pasngr', 'Low', 'Completed', now(), now(), now()),
(123, 'Books', 'Fx 1st metacarp base-opn', 'High', 'Pending', now(), now(), now()),
(124, 'Books', 'Joint pain-unspec', 'Low', 'Pending', now(), now(), now()),
(125, 'Baby', 'Adoles postural kyphosis', 'Low', 'Completed', now(), now(), now()),
(126, 'Computers', 'War inj:guided missile', 'High', 'Pending', now(), now(), now()),
(127, 'Health', 'Hyp ht/kd NOS st V w hf', 'Low', 'Pending', now(), now(), now()),
(128, 'Health', 'Epispadias', 'High', 'Pending', now(), now(), now()),
(129, 'Automotive', 'Chr inflam NOS, orbit', 'High', 'Completed', now(), now(), now()),
(130, 'Tools', 'NB intraven hem NOS', 'Medium', 'Completed', now(), now(), now()),
(131, 'Industrial', 'Rhinoscleroma', 'Low', 'Pending', now(), now(), now()),
(132, 'Grocery', 'Nodular lymphoma head', 'Low', 'Completed', now(), now(), now()),
(133, 'Automotive', 'Burn NOS leg-multiple', 'Low', 'Completed', now(), now(), now()),
(134, 'Sports', 'Epilepsy-antepartum', 'High', 'Completed', now(), now(), now()),
(135, 'Sports', 'Lactat dis NOS-del w p/p', 'High', 'Pending', now(), now(), now()),
(136, 'Baby', 'Assault-explosive NOS', 'Medium', 'Pending', now(), now(), now()),
(137, 'Grocery', 'Tenosynov hand/wrist NEC', 'Medium', 'Pending', now(), now(), now()),
(138, 'Industrial', 'Fam hx-lymph neoplas NEC', 'Low', 'Pending', now(), now(), now()),
(139, 'Music', 'Diphtheritic cystitis', 'Low', 'Pending', now(), now(), now()),
(140, 'Electronics', 'Toxic myopathy', 'Medium', 'Completed', now(), now(), now()),
(141, 'Clothing', 'Mv traff acc-anim rider', 'Medium', 'Completed', now(), now(), now()),
(142, 'Beauty', 'Hemophagocytic syndromes', 'Low', 'Completed', now(), now(), now()),
(143, 'Home', 'Joint pain-l/leg', 'High', 'Pending', now(), now(), now()),
(144, 'Beauty', 'Radiotherapy follow-up', 'Medium', 'Completed', now(), now(), now()),
(145, 'Kids', 'Gingival recession-local', 'Medium', 'Pending', now(), now(), now()),
(146, 'Computers', 'Periostitis-forearm', 'Medium', 'Completed', now(), now(), now()),
(147, 'Outdoors', 'TB of bronchus-unspec', 'Low', 'Pending', now(), now(), now()),
(148, 'Movies', 'TB thorax node-exam unkn', 'High', 'Pending', now(), now(), now()),
(149, 'Beauty', 'Opn skul fx NEC-coma NOS', 'High', 'Completed', now(), now(), now()),
(150, 'Shoes', 'Malignant neo mandible', 'High', 'Pending', now(), now(), now()),
(151, 'Jewelry', 'SIRS, NOS', 'Low', 'Pending', now(), now(), now()),
(152, 'Toys', 'Carcinoma in situ vagina', 'Low', 'Pending', now(), now(), now()),
(153, 'Computers', 'Varicose vulva-del w p/p', 'Medium', 'Pending', now(), now(), now()),
(154, 'Electronics', 'Ac stomach ulcer w perf', 'Low', 'Completed', now(), now(), now()),
(155, 'Jewelry', 'Pupillary abnormalities', 'Medium', 'Completed', now(), now(), now()),
(156, 'Tools', 'Lung anomaly NOS', 'High', 'Completed', now(), now(), now()),
(157, 'Health', 'Adhesion tymp-promontor', 'Medium', 'Pending', now(), now(), now()),
(158, 'Outdoors', 'Tachypnea', 'Medium', 'Completed', now(), now(), now()),
(159, 'Home', 'Fold of bowman membrane', 'Low', 'Pending', now(), now(), now()),
(160, 'Baby', 'Cutaneous diphtheria', 'Low', 'Pending', now(), now(), now()),
(161, 'Kids', 'Blister foot & toe-infec', 'Low', 'Pending', now(), now(), now()),
(162, 'Sports', 'Personl hx infection CNS', 'High', 'Pending', now(), now(), now()),
(163, 'Movies', 'Peritoneal dialysis test', 'High', 'Pending', now(), now(), now()),
(164, 'Electronics', 'Osteodystrophy NEC', 'Medium', 'Pending', now(), now(), now()),
(165, 'Clothing', 'Cardiovas sys symp NEC', 'Medium', 'Pending', now(), now(), now()),
(166, 'Sports', 'Intraspinal abscess', 'High', 'Completed', now(), now(), now()),
(167, 'Outdoors', 'Hyposmolality', 'Low', 'Completed', now(), now(), now()),
(168, 'Kids', 'Ben neo nasal cav/sinus', 'Medium', 'Completed', now(), now(), now()),
(169, 'Kids', 'Bullous keratopathy', 'Low', 'Completed', now(), now(), now()),
(170, 'Games', 'Louse-borne typhus', 'High', 'Pending', now(), now(), now()),
(171, 'Home', 'Open wound of elbow', 'Medium', 'Completed', now(), now(), now()),
(172, 'Garden', 'Dislocation ear ossicle', 'High', 'Completed', now(), now(), now()),
(173, 'Games', 'Somat dysfunc lower extr', 'Low', 'Pending', now(), now(), now()),
(174, 'Computers', 'Cong valgus foot def NEC', 'Medium', 'Pending', now(), now(), now()),
(175, 'Grocery', 'Deliver-twins, both sb', 'Low', 'Completed', now(), now(), now()),
(176, 'Baby', 'Amebic liver abscess', 'Medium', 'Completed', now(), now(), now()),
(177, 'Automotive', 'Fusion w def stereopsis', 'Medium', 'Completed', now(), now(), now()),
(178, 'Kids', 'Winds/brass instru play', 'Low', 'Completed', now(), now(), now()),
(179, 'Health', 'Vestibular neuronitis', 'High', 'Completed', now(), now(), now()),
(180, 'Baby', 'Fx cuboid-closed', 'Low', 'Pending', now(), now(), now()),
(181, 'Baby', 'Congen bowing of femur', 'Medium', 'Pending', now(), now(), now()),
(182, 'Industrial', 'Postlaminect synd-thorac', 'Medium', 'Completed', now(), now(), now()),
(183, 'Electronics', 'Anterior cord synd/c1-c4', 'Low', 'Pending', now(), now(), now()),
(184, 'Computers', 'Agenesis of uterus', 'High', 'Pending', now(), now(), now()),
(185, 'Shoes', 'Syphilitic peritonitis', 'Low', 'Completed', now(), now(), now()),
(186, 'Clothing', 'Ankyl vert hyperostosis', 'High', 'Completed', now(), now(), now()),
(187, 'Toys', 'Cardiogenic shock', 'Low', 'Pending', now(), now(), now()),
(188, 'Shoes', 'Chondrocalcin NOS-unspec', 'Low', 'Pending', now(), now(), now()),
(189, 'Industrial', 'RR coll NOS-ped cyclist', 'High', 'Pending', now(), now(), now()),
(190, 'Automotive', 'Threatened abort-unspec', 'High', 'Pending', now(), now(), now()),
(191, 'Jewelry', 'Fracture one rib-open', 'Medium', 'Pending', now(), now(), now()),
(192, 'Industrial', 'Anphyl react oth sp food', 'Low', 'Pending', now(), now(), now()),
(193, 'Garden', 'Elev ca-embryoic antigen', 'High', 'Completed', now(), now(), now()),
(194, 'Health', 'Hx in utero proc fetus', 'High', 'Completed', now(), now(), now()),
(195, 'Movies', 'Ulceratve colitis unspcf', 'Low', 'Pending', now(), now(), now()),
(196, 'Industrial', 'Vernal conjunctivitis', 'Medium', 'Pending', now(), now(), now()),
(197, 'Industrial', 'Prev c-delivery-delivrd', 'Low', 'Completed', now(), now(), now()),
(198, 'Home', 'Tick-borne ricketts NEC', 'Medium', 'Completed', now(), now(), now()),
(199, 'Movies', 'Stress fx pelvis', 'Medium', 'Pending', now(), now(), now()),
(200, 'Clothing', 'TB of mastoid-oth test', 'High', 'Pending', now(), now(), now())
